### ISSUE TITLE
Legacy branch download actually downloads the new rust code version

### ISSUE THREAD

**Issue by cedrictineo** [nhedger/iddns#14]
trying to download the legacy version at this link: https://github.com/nhedger/iddns/archive/master.zip actually downloads a .zip archive containing the rust version and not the legacy version. Therefore making it impossible to install the legacy version.

**Comment by nhedger** [comment]
Good catch, thanks for reporting.

I've updated the download link and instructions.

You can grab it here: https://github.com/nhedger/iddns/archive/legacy.zip

**Comment by cedrictineo** [comment]
thanks! Your tool is super useful, thank you for your work - looking forward to testing / using your new version when it's out/stable.
