### ISSUE TITLE
Erreur à l'installation "make install" sur FreeBSD

### ISSUE THREAD

**Issue by cedrictineo** [nhedger/iddns#5]
lorsque je tente make install à l'intérieur du répertoire iddns-master, j'obtiens:

Système FreeBSD 13.0p6

Merci pour ton aide, ce serait super de pouvoir faire fonctionner ton script sur FreeBSD.

````
root@ABCH001:~/iddns-master # make install
cp iddns.sh /usr/local/bin/iddns
cp --backup --suffix=.orig config.example /root/.iddns
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpsvx] source_file ... target_directory
*** Error code 64

Stop.
make: stopped in /root/iddns-master
````

**Comment by nhedger** [comment]
Salut @cedrictineo,

Merci pour ton issue.

À priori le soucis vient de l'utilisation d'option qui ne sont pas supportée avec `cp` sous FreeBSD. J'ai réimplémenté la fonctionnalité avec un bout de code un peu plus portable.

J'ai testé dans une VM et ça a l'air de fonctionner. N'hésites pas à me faire signe si tu rencontres d'autres soucis.

**Comment by cedrictineo** [comment]
Super tout fonctionne (end to end). Merci pour la super-réactivité et pour ce script qui me facilite bien la vie...
DynDNS et Oracle se comportent de façon très incorrecte - et je voulais changer depuis un moment - merci d'avoir fait ce script et de l'avoir mis dans le domaine public.

petit point qui pourrait être rajouté dans la doc - c'est que si on utilise -g ou le champ IDDNS_GRABBER dans le fichier de config - on a alors pas besoin de spécifier l'option -i ou mettre une valeur dans le champ IDDNS_IP - c'était un point de confusion pour moi, mais c'est peut-être que moi.
